### ISSUE TITLE
sticker bug

### ISSUE THREAD

**Issue by pengengantibaju** [bolaxd/ballbotV2#7]
![image](https://user-images.githubusercontent.com/92777707/200569728-82170616-46c2-4afd-9c31-da95f998b52b.png)

**Comment by bolaxd** [comment]
> ![image](https://user-images.githubusercontent.com/92777707/200569728-82170616-46c2-4afd-9c31-da95f998b52b.png)

Tambahin ini coba bang di settings.js
Mohon maaf saya kelupaan :v
// Diatas
import fs from 'node:fs';

// di paling bawah sebelum kurung
tmp: async(fileWithPath) => await fs.renameSync(fileWithPath, fileWithPath+'.tmp'),
