### ISSUE TITLE
Bagi Node Modulesnya Lah...

### ISSUE THREAD

**Issue by tahaluindo** [bolaxd/ballbotV2#8]
Hehehe

**Comment by WahyuPR0** [comment]
Aowkwkwk bangsat

**Comment by bolaxd** [comment]
Coba cek di package.json, lihat ada xfarr-api: "^2.0.0" dan baileys: "^6.0.5"
Coba xfarr-api delete saja, dan baileys nya turunin versinya ke 5.0.8

**Comment by bolaxd** [comment]
Itu yg membuat error sewaktu install node_modules, karna xfarr-api ada beberapa dependesi nya yg tidak support, harus memakai yarn install jika ingin install all module

**Comment by bolaxd** [comment]
Tinggal cek package.json dan ganti versi baileys ke 5.0.8 dan delete xfarr-api
